id = "klar"
name = "Klar"
version = "0.0.1"
schema_version = 1
authors = ["ProCode Software"]
description = "Klar support."
repository = "https://github.com/ProCode-Software/klar/tree/main/packages/klar-zed"

[language_servers.klarls]
name = "KlarLS"
languages = ["Klar", "Klon"]

[grammars.klar]
repository = "https://github.com/klarlanguage/tree-sitter-klar"
rev = "578bd06a6be41e82868b0128ea61df8cf2694327"

[grammars.klon]
repository = "https://github.com/klarlanguage/tree-sitter-klon"
rev = "4b38ff83d29c2a195bfa4ad91be23d039295bce5"

[grammars.glaslock]
repository = "https://github.com/klarlanguage/tree-sitter-glaslock"
rev = "86b7b92d6a68eb03e12e8a51993f44e1aae54b9d"
