id = "klar"
name = "Klar"
version = "0.0.1"
schema_version = 1
authors = ["ProCode Software"]
description = "Klar support."
repository = "https://github.com/ProCode-Software/klar/tree/main/packages/klar-zed"

[language_servers.klarls]
name = "KlarLS"
languages = ["Klar", "Klon"] # glas.lock files don't need LSP support

[grammars.klar]
repository = 'https://github.com/ProCode-Software/klar'
path = 'packages/tree-sitter-klar'
rev = 'e39798b825d16d746318729d4c12e51b390a2dc0'

[grammars.klon]
repository = 'https://github.com/ProCode-Software/klar'
path = 'packages/tree-sitter-klon'
rev = 'e39798b825d16d746318729d4c12e51b390a2dc0'

[grammars.glaslock]
repository = 'https://github.com/ProCode-Software/klar'
path = 'packages/tree-sitter-glaslock'
rev = 'e39798b825d16d746318729d4c12e51b390a2dc0'
