name = "glas.lock" # TODO: glas.lock or Glas Lockfile?
grammar = "glaslock"
path_suffixes = ["glas.lock"]
line_comments = ["# "]
tab_size = 4
hard_tabs = false
autoclose_before = ";:.,=}])>"
brackets = []
